image: node

before_script:
  - apt-get update && apt-get -y upgrade
  - apt-get install -y jq pandoc
  - cd pages
  - yarn

cache:
  paths:
    - node_modules/

pages:
  script:
    - ./generate.sh > src/static/data.json
    - yarn generate || true
  artifacts:
    paths:
      - pages/public
  only:
    - master
